# Generated by Django 2.1.3 on 2018-11-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.FloatField()),
                ('batch_size', models.IntegerField()),
                ('data_type', models.CharField(max_length=15)),
                ('sorting_type', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sorting_result',
            },
        ),
    ]
